# -- Deploy Argo CD Applications within this helm release
# @default -- `{}` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications:
  inreach-apps:
    name: inreach-apps
    namespace: argocd
    project: default
    source:
      repoURL: git@github.com:YKal08/InReach.git
      targetRevision: main
      path: argocd
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

projects: {}
applicationsets: {}
itemTemplates: []
extensions: {}
